import { useState } from 'react';
import { Plus, Pencil, Trash2, Search } from 'lucide-react';
import type { Resource } from '../types';
import { organizations, scenarios } from '../data/catalog';
import Modal from './Modal';
const split=(text:string)=>text.split(',').map(s=>s.trim()).filter(Boolean);
export default function Admin({resources,save}:{resources:Resource[];save:(r:Resource[])=>boolean}){
 const [editing,setEditing]=useState<Resource|null>(null),[removing,setRemoving]=useState<Resource|null>(null),[query,setQuery]=useState(''),[notice,setNotice]=useState('');
 function create(){setEditing({id:crypto.randomUUID(),name:'',organizationId:organizations[0].id,quantity:1,capacity:'',transport:'Fahrzeug',personnel:'',description:'',components:[],categories:[],scenarios:[],tags:[],confirmedAt:new Date().toISOString().slice(0,10),requestPath:'Fiktiver Anforderungsweg: über die zuständige Leitstelle. Keine Alarmierung in diesem Prototyp.'})}
 const filtered=resources.filter(r=>r.name.toLowerCase().includes(query.toLowerCase()));
 return <><div className="heading-row"><div><p className="eyebrow">LOKALER DATENBESTAND</p><h1>Verwaltung</h1><p className="lead">Fiktive Einsatzmittel auf diesem Gerät pflegen.</p></div><button className="primary" onClick={create}><Plus size={20}/>Einsatzmittel anlegen</button></div><div className="notice">Änderungen werden nur in diesem Browser gespeichert. Keine Anmeldung und keine Synchronisation.</div>{notice&&<p role="status" className="success">{notice}</p>}<div className="search-wrap"><Search size={22}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Verwaltung durchsuchen …" aria-label="Verwaltung durchsuchen"/></div><div className="admin-list">{filtered.map(r=><div className="admin-row" key={r.id}><span><strong>{r.name}</strong><small>{organizations.find(o=>o.id===r.organizationId)?.name} · {r.categories.join(', ')||'Nicht kategorisiert'}</small></span><button className="secondary" onClick={()=>setEditing(structuredClone(r))} aria-label={`${r.name} bearbeiten`}><Pencil size={17}/><span>Bearbeiten</span></button><button className="icon-button danger" aria-label={`${r.name} löschen`} onClick={()=>setRemoving(r)}><Trash2 size={19}/></button></div>)}{!filtered.length&&<div className="empty">Keine Einsatzmittel gefunden.</div>}</div>
 {editing&&<Modal title={resources.some(r=>r.id===editing.id)?'Einsatzmittel bearbeiten':'Einsatzmittel anlegen'} onClose={()=>setEditing(null)}><form className="editor-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const value=(k:string)=>String(f.get(k)||'').trim();const next:Resource={...editing,name:value('name'),organizationId:value('organizationId'),quantity:Number(value('quantity')),capacity:value('capacity'),transport:value('transport'),personnel:value('personnel'),description:value('description'),components:split(value('components')),categories:split(value('categories')),tags:split(value('tags')),scenarios:f.getAll('scenarios').map(String),confirmedAt:value('confirmedAt'),requestPath:value('requestPath')};if(!next.name||!next.capacity||!next.description||!next.personnel||!next.transport||!next.requestPath){setNotice('Bitte alle Pflichtfelder mit Text ausfüllen.');return}if(save(resources.some(r=>r.id===next.id)?resources.map(r=>r.id===next.id?next:r):[...resources,next])){setNotice('Einsatzmittel lokal gespeichert.');setEditing(null)}}}>
 <label>Bezeichnung *<input name="name" required maxLength={120} defaultValue={editing.name}/></label><div className="form-grid"><label>Organisation *<select name="organizationId" defaultValue={editing.organizationId}>{organizations.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><label>Anzahl *<input type="number" min="1" max="99999" step="1" name="quantity" required defaultValue={editing.quantity}/></label></div><label>Leistung / technische Daten *<input name="capacity" required defaultValue={editing.capacity}/></label><div className="form-grid"><label>Transportart *<input name="transport" required defaultValue={editing.transport}/></label><label>Erforderliches Personal *<input name="personnel" required defaultValue={editing.personnel}/></label></div><label>Beschreibung *<textarea name="description" required rows={3} defaultValue={editing.description}/></label><label>Begleitkomponenten (mit Komma trennen)<input name="components" defaultValue={editing.components.join(', ')}/></label><label>Ressourcengruppen (optional, mit Komma trennen)<input name="categories" defaultValue={editing.categories.join(', ')}/></label><label>Tags (mit Komma trennen)<input name="tags" defaultValue={editing.tags.join(', ')}/></label><fieldset><legend>Einsatzbereiche</legend><div className="checkbox-grid">{scenarios.slice(0,-1).map(s=><label key={s}><input type="checkbox" name="scenarios" value={s} defaultChecked={editing.scenarios.includes(s)}/>{s}</label>)}</div></fieldset><label>Letzte Datenbestätigung *<input type="date" name="confirmedAt" required defaultValue={editing.confirmedAt}/></label><label>Anforderungsweg (nur Information) *<textarea name="requestPath" required rows={3} defaultValue={editing.requestPath}/></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Abbrechen</button><button className="primary" type="submit">Lokal speichern</button></div></form></Modal>}
 {removing&&<Modal title="Einsatzmittel löschen" onClose={()=>setRemoving(null)}><div className="detail-content"><h2>„{removing.name}“ löschen?</h2><p>Die Ressource wird aus diesem lokalen Katalog entfernt.</p><div className="form-actions"><button className="secondary" onClick={()=>setRemoving(null)}>Abbrechen</button><button className="primary destructive" onClick={()=>{if(save(resources.filter(r=>r.id!==removing.id))){setRemoving(null);setNotice('Einsatzmittel gelöscht.')}}}>Löschen</button></div></div></Modal>}</>
}
